const { MessageEmbed } = require('discord.js')

module.exports = async (client, args, message) => {
    const helpEmbed = new MessageEmbed()
        .setTitle("Help")
        .setDescription("[] means optional, <> means required")
        .addField("Prefix", ";")
        .addField(":gear: Useful Commands :gear:", "Commands than ban, clear, kick, and get info!")
        .addField("Client's Ping", "ping", true)
        .addField("Bulk Delete", "clear <number>", true)
        .addField("Ban Member", "ban <member> <reason>", true)
        .addField("Kick Member", "kick <member> <reason>", true)
        .addField('Warn Member', 'warn <member> <reason>', true)
        .addField(":partying_face: Fun Commands :partying_face:", "Commands that are fun!")
        .addField('Laughing Your Meme\'s Out', 'meme', true)
        .addField('Let your path be chosen', '8ball <question>', true)
        .addField('What\'s your number?', 'randnum', true)
        .addField('Search for some images!', 'search <term>')
        .addField(':musical_note: Music Commands :musical_note:', 'Music Commands!')
        .addField("Music Play", "play <search / URL>", true)
        .addField("Music Stop", "stop", true)
        .addField(':blue_square: Minecraft Commands :blue_square:', 'Some blocky commands!')
        .addField("Minecraft Server", "ms <IP> [port]", true)
        .addField('Minecraft Server List', 'msl', true)
        .addField('Make sure to report any bugs you find', 'report <report>')
        .addField("Invite Me!", ";invite")
        .addField('Join the support server!', 'https://discord.gg/cUYrWbX')
        .setColor('GREEN')

    message.channel.send(helpEmbed)
}